In [4]:
import numpy as np

In [4]:
arreglo_nmeros = np.array([1,2,3])
print(arreglo_nmeros)

[1 2 3]


In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3))

array([0., 0., 0.])

In [7]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.empty((5))

array([1., 1., 1., 1., 1.])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(3)

array([0, 1, 2])

In [16]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.arange(3,50)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
print(np.arange(12))
print(np.arange(3,50))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
print(np.arange(4,20,2))

[ 4  6  8 10 12 14 16 18]


In [21]:
arreglo_dimension = np.array([(1,2,3),(4,5,6)])
arreglo_dimension.shape

(2, 3)

In [23]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
np.ones_like(np.arange(6).reshape(3,2))

array([[1, 1],
       [1, 1],
       [1, 1]])

In [25]:
np.ones_like(np.arange(3))

array([1, 1, 1])

In [27]:
np.arange(24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [28]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [32]:
np.arange(100000).reshape(100,100,10)

array([[[    0,     1,     2, ...,     7,     8,     9],
        [   10,    11,    12, ...,    17,    18,    19],
        [   20,    21,    22, ...,    27,    28,    29],
        ...,
        [  970,   971,   972, ...,   977,   978,   979],
        [  980,   981,   982, ...,   987,   988,   989],
        [  990,   991,   992, ...,   997,   998,   999]],

       [[ 1000,  1001,  1002, ...,  1007,  1008,  1009],
        [ 1010,  1011,  1012, ...,  1017,  1018,  1019],
        [ 1020,  1021,  1022, ...,  1027,  1028,  1029],
        ...,
        [ 1970,  1971,  1972, ...,  1977,  1978,  1979],
        [ 1980,  1981,  1982, ...,  1987,  1988,  1989],
        [ 1990,  1991,  1992, ...,  1997,  1998,  1999]],

       [[ 2000,  2001,  2002, ...,  2007,  2008,  2009],
        [ 2010,  2011,  2012, ...,  2017,  2018,  2019],
        [ 2020,  2021,  2022, ...,  2027,  2028,  2029],
        ...,
        [ 2970,  2971,  2972, ...,  2977,  2978,  2979],
        [ 2980,  2981,  2982, ...,  2987,  29

In [33]:
# Sumas
a = np.array([10,10,10])
b= np.array([5,5,5])

print(a + b)

[15 15 15]


In [34]:
# Resta
print(a  - b)

[5 5 5]


In [35]:
# Multiplicación
print(a*b)

[50 50 50]


In [36]:
# División
print(a/b)

[2. 2. 2.]


In [38]:
arreglo_diez_ocho = np.arange(18)
print(arreglo_diez_ocho/2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


In [40]:
print(type(arreglo_diez_ocho))

<class 'numpy.ndarray'>


In [41]:
print(arreglo_diez_ocho%3)

[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]


In [42]:
# Expresiones
print(arreglo_diez_ocho > 9)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True]


In [48]:
# Multiplicaiones de varias dimensiones
A = np.arange(4).reshape(2,2)
print(A)

B = np.arange(4,8).reshape(2,2)
print(B)

A % B

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


array([[0, 1],
       [2, 3]], dtype=int32)

In [49]:
# Multiplicación en cruz
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [50]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [52]:
arreglo_tres = np.arange(3)
arreglo_tres += 3
print(arreglo_tres)

[3 4 5]


In [54]:
# Operacaiones conocidas en los arreglos
arreglo_diez_elementos = np.arange(10)
print(arreglo_diez_elementos)
print(arreglo_diez_elementos.sum())
print(arreglo_diez_elementos.min())
print(arreglo_diez_elementos.max())

[0 1 2 3 4 5 6 7 8 9]
45
0
9


In [56]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
print(arreglo_tres_cuatro)
print(arreglo_tres_cuatro.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]


In [64]:
# Universal FUnctions
## Radianes
angulos_cero_noventa = np.arange(0,100,15)
print(angulos_cero_noventa)
angulos_cero_noventa_radiaones = angulos_cero_noventa * np.pi/180
print(angulos_cero_noventa_radiaones)
print(np.pi)

[ 0 15 30 45 60 75 90]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
3.141592653589793


In [65]:
print(np.sin(angulos_cero_noventa))

[ 0.          0.65028784 -0.98803162  0.85090352 -0.30481062 -0.38778164
  0.89399666]


In [66]:
print(np.cos(angulos_cero_noventa))

[ 1.         -0.75968791  0.15425145  0.52532199 -0.95241298  0.92175127
 -0.44807362]


In [67]:
print(np.tan(angulos_cero_noventa))

[ 0.         -0.8559934  -6.4053312   1.61977519  0.32004039 -0.42070095
 -1.99520041]


In [68]:
arreglo_diez = np.arange(10)
print(arreglo_diez)
print(np.mean(arreglo_diez))

[0 1 2 3 4 5 6 7 8 9]
4.5


In [69]:
print(np.median(arreglo_diez))

4.5


In [73]:
arreglo_diez = np.random.rand(30)*10
print(arreglo_diez)

[9.64263331 1.8444569  7.61819746 8.91660348 5.68029053 5.6534976
 6.52919216 6.15659596 2.03458372 1.29738023 8.12374169 7.70648305
 1.5270041  9.38486549 3.56353806 9.6408912  7.47754877 6.71036171
 0.12063186 5.57513758 3.13525696 5.56172346 7.27969355 4.07080982
 8.41011396 0.83062943 0.82619677 4.34636955 7.2809505  5.21543903]


In [74]:
print(np.mean(arreglo_diez))
print(np.median(arreglo_diez))

5.405360595725657
5.666894064392364


In [75]:
# Desviacion estándar
print(arreglo_diez)
print(np.std(arreglo_diez))

[9.64263331 1.8444569  7.61819746 8.91660348 5.68029053 5.6534976
 6.52919216 6.15659596 2.03458372 1.29738023 8.12374169 7.70648305
 1.5270041  9.38486549 3.56353806 9.6408912  7.47754877 6.71036171
 0.12063186 5.57513758 3.13525696 5.56172346 7.27969355 4.07080982
 8.41011396 0.83062943 0.82619677 4.34636955 7.2809505  5.21543903]
2.8459561920843446


In [76]:
print(np.var(arreglo_diez))

8.099466647263224


In [77]:
# salarios
salarios = np.genfromtxt('data/salarios.csv', delimiter=',')
print(salarios)

OSError: data/salarios.csv not found.

In [78]:
# Slice and Dice
arreglo_once_cuadrado = np.arange(11)**2
print(arreglo_once_cuadrado)

[  0   1   4   9  16  25  36  49  64  81 100]


In [79]:
print(arreglo_once_cuadrado[0])

0


In [82]:
print(arreglo_once_cuadrado[-3])

64


In [83]:
print(arreglo_once_cuadrado[0:3])

[0 1 4]


In [84]:
print(arreglo_once_cuadrado[2:-3])

[ 4  9 16 25 36 49]


In [85]:
print(arreglo_once_cuadrado[-8:-1])

[ 9 16 25 36 49 64 81]


In [86]:
print(arreglo_once_cuadrado[1:])

[  1   4   9  16  25  36  49  64  81 100]


In [88]:
print(arreglo_once_cuadrado[:5])

[ 0  1  4  9 16]


In [90]:
print(arreglo_once_cuadrado[2:8:4])

[ 4 36]


In [92]:
print(arreglo_once_cuadrado[:10:2])

[ 0  4 16 36 64]


In [93]:
print(arreglo_once_cuadrado[::-1])

[100  81  64  49  36  25  16   9   4   1   0]


In [5]:
estudiantes = np.array([['Adrian', 'Carlos', 'Vicente', 'Felipe'], [1,2,3,4],[6.5,7.5,8,9]]);

In [6]:
estudiantes

array([['Adrian', 'Carlos', 'Vicente', 'Felipe'],
       ['1', '2', '3', '4'],
       ['6.5', '7.5', '8', '9']], dtype='<U7')

In [15]:
for estudiante in estudiantes.flatten(order="F"):
    print(estudiante)


Adrian
1
6.5
Carlos
2
7.5
Vicente
3
8
Felipe
4
9


In [14]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
arreglo_tres_cuatro

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
# nditer
for i in np.nditer(arreglo_tres_cuatro):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
for i in np.nditer(arreglo_tres_cuatro, order="F", op_flags=["readwrite"]):
    print(i)
    i[...] = i*i
    print(i)

0
0
4
16
8
64
1
1
5
25
9
81
2
4
6
36
10
100
3
9
7
49
11
121


In [35]:
# Reshape
paises_tuplas = np.array([('Ecuador','Colombia', 'Peru', 'Brasil')
                          ,('Mexico', 'Guatemala', 'Honduras', 'Venezuela')]);

In [18]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brasil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [22]:
paises_tuplas[0][0] = 'Estados Unidos'

In [25]:
paises_tuplas[0][0]

'Ecuador'

In [26]:
paises_tuplas.shape

(2, 4)

In [27]:
paises_tuplas.flatten()

array(['Ecuador', 'Colombia', 'Peru', 'Brasil', 'Mexico', 'Guatemala',
       'Honduras', 'Venezuela'], dtype='<U9')

In [28]:
paises_tuplas

array([['Ecuador', 'Colombia', 'Peru', 'Brasil'],
       ['Mexico', 'Guatemala', 'Honduras', 'Venezuela']], dtype='<U9')

In [29]:
paises_tuplas.T

array([['Ecuador', 'Mexico'],
       ['Colombia', 'Guatemala'],
       ['Peru', 'Honduras'],
       ['Brasil', 'Venezuela']], dtype='<U9')

In [30]:
paises_tuplas.T.flatten()

array(['Ecuador', 'Mexico', 'Colombia', 'Guatemala', 'Peru', 'Honduras',
       'Brasil', 'Venezuela'], dtype='<U9')

In [31]:
paises_tuplas.reshape(4,2)

array([['Ecuador', 'Colombia'],
       ['Peru', 'Brasil'],
       ['Mexico', 'Guatemala'],
       ['Honduras', 'Venezuela']], dtype='<U9')

In [39]:
paises = np.array([
    'Ecuador',
    'Colombia', 
    'Peru', 
    'Brasil',
    'Mexico', 
    'Guatemala', 
    'Honduras', 
    'Venezuela',
    'Argentina', 
    'Chile',
    'Bolivia',
    'Alemania']);

In [40]:
paises.shape

(12,)

In [43]:
paises.reshape(-1,3) # 9 9 = x*3  x = 9/3 = 3

array([['Ecuador', 'Colombia', 'Peru'],
       ['Brasil', 'Mexico', 'Guatemala'],
       ['Honduras', 'Venezuela', 'Argentina'],
       ['Chile', 'Bolivia', 'Alemania']], dtype='<U9')

In [46]:
arreglo_split = np.arange(1,13)

In [47]:
arreglo_split

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
np.split(arreglo_split,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [50]:
np.split(arreglo_split,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [52]:
np.split(arreglo_split,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [53]:
np.split(arreglo_split,[2,3,6,8])

[array([1, 2]),
 array([3]),
 array([4, 5, 6]),
 array([7, 8]),
 array([ 9, 10, 11, 12])]

In [58]:
paises = np.array([
    'Ecuador',
    'Colombia', 
    'Peru', 
    'Brasil',
    'Mexico', 
    'Guatemala', 
   ]);

In [59]:
np.hsplit(paises,2)

[array(['Ecuador', 'Colombia', 'Peru'], dtype='<U9'),
 array(['Brasil', 'Mexico', 'Guatemala'], dtype='<U9')]

In [60]:
np.vsplit(paises,2)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [61]:
paises_2d = np.array([['Ecuador', 'Colombia', 'Peru'],['Brazil', 'Mexico', 'Gutemala']])

In [69]:
print(paises_2d)
np.vsplit(paises_2d,2)

[['Ecuador' 'Colombia' 'Peru']
 ['Brazil' 'Mexico' 'Gutemala']]


[array([['Ecuador', 'Colombia', 'Peru']], dtype='<U8'),
 array([['Brazil', 'Mexico', 'Gutemala']], dtype='<U8')]

In [64]:
np.hsplit(paises_2d,3)

[array([['Ecuador'],
        ['Brazil']], dtype='<U8'), array([['Colombia'],
        ['Mexico']], dtype='<U8'), array([['Peru'],
        ['Gutemala']], dtype='<U8')]