In [1]:
import numpy as np

In [2]:
salarios = np.genfromtxt('datos/salary.csv', delimiter=',')
salarios

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [3]:
salarios.max()

850000.0

In [4]:
np.argmax(salarios)

246

In [5]:
np.argmin(salarios)

282

In [6]:
salarios[282]

11400.0

In [7]:
np.argsort(salarios)

array([282, 969, 606, ..., 829, 389, 246], dtype=int64)

In [8]:
np.argsort(salarios, kind="mergesort")

array([282, 969, 606, ..., 829, 389, 246], dtype=int64)

In [10]:
indices_mayores_a_cincuentamil = np.where(salarios > 50000)
indices_mayores_a_cincuentamil

(array([   0,    1,    2,    3,    4,    9,   15,   21,   22,   24,   27,
          28,   29,   31,   32,   33,   34,   36,   37,   38,   42,   44,
          45,   46,   48,   49,   51,   52,   55,   59,   60,   67,   68,
          69,   75,   77,   78,   79,   81,   83,   84,   87,   88,   91,
          92,   94,   95,   96,   97,  102,  105,  106,  107,  109,  110,
         111,  115,  117,  118,  119,  123,  125,  127,  139,  142,  146,
         151,  153,  156,  158,  161,  162,  172,  173,  177,  178,  182,
         183,  185,  192,  193,  194,  195,  196,  197,  198,  202,  212,
         216,  217,  220,  221,  233,  234,  236,  237,  238,  239,  241,
         242,  243,  244,  246,  249,  252,  256,  257,  260,  270,  271,
         273,  277,  278,  280,  281,  283,  286,  288,  289,  290,  292,
         293,  295,  296,  297,  300,  301,  302,  303,  305,  306,  311,
         312,  315,  316,  321,  322,  326,  329,  332,  333,  334,  335,
         337,  339,  343,  344,  346, 

In [13]:
salarios[indices_mayores_a_cincuentamil]
condicion_media = salarios > np.mean(salarios)
condicion_media

array([ True,  True,  True, ..., False, False,  True])

In [14]:
salarios[condicion_media]

array([ 60000.,  58000.,  56967.,  70000.,  75000.,  62000.,  56000.,
       261546.,  77000., 500000.,  77570.,  60000.,  65000.,  60000.,
       120000.,  81000.,  75000.,  75000.,  73000.,  75000., 210000.,
        90000., 105227.,  84000.,  98000.,  70000., 115000.,  72000.,
        57400.,  70000.,  71796., 130773., 103529.,  57000.,  70000.,
        75000.,  57000., 119875.,  60000., 132000., 100000., 141671.,
        87500.,  90000.,  65000., 109100.,  98080.,  87689., 550000.,
        56697.,  60000., 180000.,  92000.,  63000., 220000.,  66000.,
        80000.,  65460.,  65000., 109294.,  70000.,  57758.,  75000.,
        75000.,  62662.,  64000.,  90000.,  60000.,  60000.,  70000.,
        63000.,  80000.,  70000.,  60000.,  90000., 135380.,  65000.,
        70000., 103529.,  64000.,  70000., 120000., 185000.,  70000.,
       850000.,  61500.,  60000.,  63000., 181339.,  75665.,  58000.,
        57000., 100000.,  65000.,  62662.,  90000.,  70835.,  75000.,
       111600., 1020

In [15]:
np.extract(condicion_media, salarios)

array([ 60000.,  58000.,  56967.,  70000.,  75000.,  62000.,  56000.,
       261546.,  77000., 500000.,  77570.,  60000.,  65000.,  60000.,
       120000.,  81000.,  75000.,  75000.,  73000.,  75000., 210000.,
        90000., 105227.,  84000.,  98000.,  70000., 115000.,  72000.,
        57400.,  70000.,  71796., 130773., 103529.,  57000.,  70000.,
        75000.,  57000., 119875.,  60000., 132000., 100000., 141671.,
        87500.,  90000.,  65000., 109100.,  98080.,  87689., 550000.,
        56697.,  60000., 180000.,  92000.,  63000., 220000.,  66000.,
        80000.,  65460.,  65000., 109294.,  70000.,  57758.,  75000.,
        75000.,  62662.,  64000.,  90000.,  60000.,  60000.,  70000.,
        63000.,  80000.,  70000.,  60000.,  90000., 135380.,  65000.,
        70000., 103529.,  64000.,  70000., 120000., 185000.,  70000.,
       850000.,  61500.,  60000.,  63000., 181339.,  75665.,  58000.,
        57000., 100000.,  65000.,  62662.,  90000.,  70835.,  75000.,
       111600., 1020